DROP TABLE BUYER CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE COUPON CASCADE CONSTRAINTS;
DROP TABLE CSC CASCADE CONSTRAINTS;
DROP TABLE FAVORITY CASCADE CONSTRAINTS;
DROP TABLE LASTORDER CASCADE CONSTRAINTS;
DROP TABLE LASTORDER_SHOPPINGCART CASCADE CONSTRAINTS;
DROP TABLE MENU CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE ORDER_TBL CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE REVIEW_REPLY CASCADE CONSTRAINTS;
DROP TABLE SHOPPINGCART CASCADE CONSTRAINTS;
DROP TABLE SUBMENU CASCADE CONSTRAINTS;
DROP TABLE SELLER CASCADE CONSTRAINTS;

DROP SEQUENCE BUYER_SEQ;
DROP SEQUENCE SELLER_SEQ;
DROP SEQUENCE MENU_SEQ;
DROP SEQUENCE REVIEW_SEQ;
DROP SEQUENCE ORDER_SEQ;
DROP SEQUENCE RECEIPT_SEQ;
DROP SEQUENCE FAVORITE_SEQ;
DROP SEQUENCE REPLY_SEQ;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE COUPON_SEQ;
DROP SEQUENCE LASTORDER_SEQ;
DROP SEQUENCE shopping_SEQ;
DROP SEQUENCE LASTORDER_SHOPPINGCART_SEQ;


CREATE SEQUENCE LASTORDER_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE shopping_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;


CREATE SEQUENCE coupon_seq  
START WITH 1     
INCREMENT BY 1   
NOMAXVALUE
NOCYCLE            
NOCACHE;



CREATE SEQUENCE FAVORITE_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE RECEIPT_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE ORDER_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE BUYER_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE REVIEW_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE SELLER_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE MENU_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;


CREATE SEQUENCE REPLY_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_NOTICE  
START WITH 1     
INCREMENT BY 1   
NOMAXVALUE
NOCYCLE            
NOCACHE;

CREATE SEQUENCE LASTORDER_SHOPPINGCART_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;


--구매자 테이블
CREATE TABLE BUYER (
    B_CODE VARCHAR2(20) PRIMARY KEY,
    B_NAME VARCHAR2(20) NOT NULL,
    B_BIRTH DATE NOT NULL,
    B_ADDR VARCHAR2(100) NOT NULL,
    B_ID VARCHAR2(20) UNIQUE,
    B_PWD VARCHAR2(20) NOT NULL,
    B_NICK VARCHAR2(20) UNIQUE,
    B_ENROLL_DATE DATE NOT NULL,
    B_PHONE VARCHAR2(20) NOT NULL,
    B_ROADNAME VARCHAR2(20)
);
--쿠폰테이블
CREATE TABLE COUPON (
    C_CODE NUMBER PRIMARY KEY,
    C_NAME VARCHAR2(20) NOT NULL,
    C_DISCOUNT VARCHAR2(20) NOT NULL,
    B_CODE VARCHAR2(20) REFERENCES BUYER(B_CODE) ON DELETE CASCADE
);
--카테고리테이블
CREATE TABLE CATEGORY (
    CATEGORY_CODE NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(20) NOT NULL
);
--판매자 테이블
CREATE TABLE SELLER (
    S_CODE VARCHAR2(20) PRIMARY KEY,
    CATEGORY_CODE NUMBER REFERENCES CATEGORY(CATEGORY_CODE) ON DELETE CASCADE,
    S_NAME VARCHAR2(20) NOT NULL,
    S_BIRTH DATE NOT NULL,
    TRUCK_ADDR VARCHAR2(100) NOT NULL,
    S_ID VARCHAR2(20) UNIQUE,
    S_PWD VARCHAR2(20) NOT NULL,
    S_NICK VARCHAR2(20) UNIQUE,
    S_COOP_NUM VARCHAR2(50) UNIQUE,
    TRUCK_NAME VARCHAR2(50) UNIQUE,
    S_PHONE VARCHAR2(20) NOT NULL,
    S_ENROLL_DATE DATE NOT NULL,
    LOGO_PHOTO VARCHAR2(100),
    LOGO_PHOTO_PATH VARCHAR2(500)
);
--소메뉴테이블
CREATE TABLE SUBMENU (
    SUBMENU_CODE NUMBER PRIMARY KEY,
    SUBMENU_NAME VARCHAR2(20) NOT NULL
);
--메뉴테이블
CREATE TABLE MENU (
    MENU_CODE NUMBER PRIMARY KEY,
    SUBMENU_CODE NUMBER REFERENCES SUBMENU(SUBMENU_CODE)ON DELETE CASCADE,
    MENU_NAME VARCHAR2(50) NOT NULL,
    PRICE NUMBER NOT NULL,
    S_CODE VARCHAR2(20) REFERENCES SELLER(S_CODE)ON DELETE CASCADE,
    CATEGORY_CODE NUMBER NOT NULL,
    DETAIL VARCHAR2(300),
    SUMMARY VARCHAR2(100),
    MENU_PHOTO VARCHAR2(100),
    MENU_PHOTO_PATH VARCHAR2(500)
);

--라스트오더 등록 테이블
CREATE TABLE LASTORDER (
    LASTORDER_CODE NUMBER PRIMARY KEY,
    STOCK NUMBER NOT NULL,
    DISCOUNT NUMBER NOT NULL,
    LAST_MENU_NAME VARCHAR2(50) NOT NULL,
    LAST_PRICE NUMBER NOT NULL,
    LAST_S_CODE VARCHAR2(20) NOT NULL,
    LAST_CATEGORY VARCHAR2(20) NOT NULL,
    LAST_DETAIL VARCHAR2(300),
    LAST_SUMMARY VARCHAR2(100),
    LAST_PHOTO VARCHAR2(100),
    LAST_PHOTO_PATH VARCHAR2(500),
    LAST_SUBMENU_CODE NUMBER(20) NOT NULL
);
--고객센터 테이블
CREATE TABLE CSC (
   CSC_CODE NUMBER PRIMARY KEY,
   CSC_TITLE VARCHAR2(200) NOT NULL,
   CSC_DATE TIMESTAMP NOT NULL,
   CSC_CONTENT VARCHAR2(500) NOT NULL,
   SESSION_CODE CHAR NOT NULL
);
--공지사항 테이블
CREATE TABLE NOTICE (
   NOTICE_CODE NUMBER PRIMARY KEY,
   NOTICE_DATE DATE NOT NULL,
   NOTICE_NAME VARCHAR2(200) NOT NULL,
   NOTICE_CONTENT VARCHAR2(1000) NOT NULL,
   ADMIN_ID VARCHAR2(20) NOT NULL,
   HITS NUMBER default 0
);
--장바구니 테이블
CREATE TABLE SHOPPINGCART (
   SHOPPINGCART_CODE NUMBER PRIMARY KEY,
   AMOUNT NUMBER NOT NULL,
   B_CODE VARCHAR2(20) REFERENCES BUYER (B_CODE) ON DELETE CASCADE,
   MENU_CODE NUMBER REFERENCES MENU (MENU_CODE) ON DELETE CASCADE,
   MENU_NAME VARCHAR2(50) NOT NULL,
   PRICE NUMBER NOT NULL,
   S_CODE VARCHAR2(20) NOT NULL
);
--주문테이블
CREATE TABLE ORDER_TBL (
   ORDER_CODE NUMBER PRIMARY KEY,
   B_ID VARCHAR2(20) NOT NULL,
   RECEIPT_CODE VARCHAR2(20) NOT NULL,
   MENU_CODE NUMBER NOT NULL,
   MENU_NAME VARCHAR2(50) NOT NULL,
   PRICE NUMBER NOT NULL,
   AMOUNT NUMBER NOT NULL,
   ORDER_STATUS VARCHAR2(20) CHECK(ORDER_STATUS IN('주문', '수락', '완료')),
   PAYMENT_WAYS VARCHAR2(20) CHECK(PAYMENT_WAYS IN('현장결제', '결제완료')), 
   S_CODE VARCHAR2(20) NOT NULL,
   TRUCK_NAME VARCHAR2(50) NOT NULL,
   B_REQUEST VARCHAR2(100),
   ORDER_DATE DATE NOT NULL
);
--라스트오더 장바구니 테이블
CREATE TABLE LASTORDER_SHOPPINGCART (
   LASTORDER_SHOPPINGCART_CODE NUMBER PRIMARY KEY,
   LASTORDER_CODE NUMBER REFERENCES LASTORDER (LASTORDER_CODE) ON DELETE CASCADE,
   B_CODE VARCHAR2(20) REFERENCES BUYER (B_CODE),
   LAST_MENU_NAME VARCHAR2(50) NOT NULL,
   LAST_PRICE NUMBER NOT NULL,
   DISCOUNT NUMBER NOT NULL,
   AMOUNT NUMBER NOT NULL,
   S_CODE VARCHAR2(20) NOT NULL
);

-- 리뷰 테이블
CREATE TABLE REVIEW (
REVIEW_CODE NUMBER PRIMARY KEY,
ORDER_CODE NUMBER NOT NULL,
S_CODE VARCHAR2(20) NOT NULL,
B_CODE VARCHAR2(20) NOT NULL,
GRADE NUMBER,
REIVEW_PHOTO VARCHAR2(100),
REVIEW_CONTENT VARCHAR2(500),
REVIEW_PHOTO_PATH VARCHAR2(500),
REVIEW_DATE TIMESTAMP NOT NULL
);
-- 리뷰 답글 테이블
CREATE TABLE REVIEW_REPLY(
REPLY_CODE NUMBER PRIMARY KEY,
REVIEW_CODE NUMBER REFERENCES REVIEW(REVIEW_CODE) ON DELETE CASCADE,
REPLY_CONTENT VARCHAR2(500),
REPLY_DATE TIMESTAMP NOT NULL
);

-- 찜한트럭 테이블
CREATE TABLE FAVORITY(
    FAVORITY_CODE NUMBER PRIMARY KEY,
    B_CODE VARCHAR2(20) NOT NULL,
    S_CODE VARCHAR2(20) NOT NULL,
    TRUCK_NAME VARCHAR2(50) NOT NULL,
    TRUCK_ADDR VARCHAR2(100) NOT NULL
);

-- 쿠폰 트리거
CREATE OR REPLACE TRIGGER COUPON_TRG
AFTER INSERT ON BUYER
FOR EACH ROW
BEGIN
    INSERT INTO COUPON VALUES(COUPON_SEQ.NEXTVAL, '신규가입 10%', 10, :NEW.B_CODE);
    INSERT INTO COUPON VALUES(coupon_seq.nextval, '깜짝 5% 세일', 5, :NEW.B_CODE);
END;
/

commit;

