-- 한식 판매자 메뉴 등록
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '곱창', 7000, 's81', 1, '돼지곱창을 풍미있게 야채와 함께 볶은 곱창볶음입니다.', '돼지곱창볶음(한접시)', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '막창', 9000, 's81', 1, '돼지막창을 풍미있게 야채와 함께 볶은 막창볶음입니다.', '돼지막창볶음(한접시)', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '대창', 9000, 's81', 1, '돼지대창을 풍미있게 야채와 함께 볶은 대창볶음입니다.', '돼지대창볶음(한접시)', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '모듬볶음', 11000, 's81', 1, '돼지곱창, 막창, 대창을 함께 볶은 모듬볶음입니다.', '모듬볶음(한접시)', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '소곱창', 12000, 's81', 1, '소곱창을 풍미있게 야채와 함께 볶은 곱창볶음입니다.', '소곱창볶음(한접시)', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 03, '알곱창', 6000, 's81', 1, '돼지 곱창만 추가로 더 들어가는 알곱창입니다.', '곱배기', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '볶음밥', 2000, 's81', 1, '곱창볶음 양념과 함께 비벼져서 볶아진 볶음밥입니다.', '볶음밥', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '염통꼬치', 3000, 's81', 1, '염통꼬치입니다.', '염통꼬치2개', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '음료', 2000, 's81', 1, '350ml 콜라와 사이다만 판매합니다.', '콜라, 사이다', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '주류', 4000, 's81', 1, '맥주와 소주만 판매합니다.', '소주, 맥주', null, null);

INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '떡볶이', 3000, 's82', 1, '맛있는 떡볶이.', '떡볶이', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '매콤떡볶이', 9000, 's82', 1, '좀 더 매운 떡볶이', '매운떡볶이', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '튀김', 2000, 's82', 1, '오징어, 만두, 고구마, 야채 등 다양한 튀김이 있습니다.', '튀김 5개', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '오뎅', 700, 's82', 1, '떡볶이하면 빠질 수 없는 오뎅입니다.', '오뎅 개당 700원', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '순대', 3000, 's82', 1, '순대입니다.', '순대', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '닭꼬치', 1500, 's82', 1, '닭꼬치입니다.', '닭꼬치', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '떡꼬치', 1000, 's82', 1, '떡꼬치입니다.', '떡꼬치', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '슬러시', 1000, 's82', 1, '슬러시입니다.', '슬러시야', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '음료', 2000, 's82', 1, '350ml 콜라와 사이다만 판매합니다.', '콜라, 사이다', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '주류', 4000, 's82', 1, '맥주와 소주만 판매합니다.', '소주, 맥주', null, null);

-- 중식 판매자 메뉴 등록
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '마라탕', 5000, 's101', 2, '떠오르는 매운맛 마라탕', '마라탕', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '쌀국수', 4000, 's101', 2, '매운거 싫어하시는 분들을 위한 메뉴입니다.', '쌀국숭', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '마라샹궈', 7000, 's101', 2, '함께 드시고싶으시면 마라샹궈', '마라샹궈', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '볶음면', 4000, 's101', 2, '볶음면입니다.', '볶음면야', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 03, '채소추가', 2000, 's101', 2, '마라탕 채소 추가입니다.', '마라탕 채소 추가', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 03, '고기추가', 3000, 's101', 2, '마라탕 고기 추가입니다.', '마라탕 고기 추가', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '고기만두', 4000, 's101', 2, '고기만두입니다.', '고기만두 조아', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '꿔바로우', 5000, 's101', 2, '찹쌀 탕수육', '꿔바로우 맛있엉', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '음료', 2000, 's101', 2, '350ml 콜라와 사이다만 판매합니다.', '콜라, 사이다', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '주류', 4000, 's101', 2, '맥주와 소주만 판매합니다.', '소주, 맥주', null, null);

INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '자장면', 5000, 's102', 2, '자장면입니다.', '자장면이야', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '짬뽕', 6000, 's102', 2, '짬뽕입니다.', '짬뽕뽀로', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '볶음밥', 5000, 's102', 2, '볶음밥입니다.', '볶음밥', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '자장밥', 6000, 's102', 2, '자장밥입니다.', '자장밥', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '짬뽕밥', 6000, 's102', 2, '짬뽕밥입니다.', '짬뽕밥', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 03, '곱배기', 1000, 's102', 2, '면과 밥류에만 곱배기가 추가됩니다.', '곱배기', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '군만두', 3000, 's102', 2, '군만두입니다.', '군만두', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '탕수육', 8000, 's102', 2, '탕수육입니다.', '탕수육', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '음료', 2000, 's102', 2, '350ml 콜라와 사이다만 판매합니다.', '콜라, 사이다', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '주류', 4000, 's102', 2, '맥주와 소주만 판매합니다.', '소주, 맥주', null, null);

-- 일식 판매자 메뉴 등록
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '로스가스', 5000, 's41', 3, '돼지 등심 돈가스입니다.', '로스가스', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '히레가스', 4000, 's41', 3, '돼지 안심 돈가스입니다.', '히레가스', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '치즈돈가스', 7000, 's41', 3, '치즈돈가스입니다.', '치즈돈가스', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '생선가스', 4000, 's41', 3, '생선가스입니다.', '생선가스', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '치킨가스', 2000, 's41', 3, '치킨가스입니다.', '치킨가스', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '새우튀김', 3000, 's41', 3, '새우튀김입니다.', '새우튀김', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '가라아게', 4000, 's41', 3, '일본식 치킨튀김입니다.', '가라아게', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '감자튀김', 5000, 's41', 3, '감자튀김입니다.', '감자튀김 조아', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '음료', 2000, 's41', 3, '350ml 콜라와 사이다만 판매합니다.', '콜라, 사이다', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '주류', 4000, 's41', 3, '맥주와 소주만 판매합니다.', '소주, 맥주', null, null);

INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '옛날우동', 3500, 's42', 3, '옛날우동입니다.', '옛날우동', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '냉모밀', 5000, 's42', 3, '냉모밀입니다.', '냉모밀', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '돈까스덮밥', 5500, 's42', 3, '돈까스덮밥입니다.', '돈까스덮밥', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '김치우동', 4000, 's42', 3, '김치우동입니다.', '김치우동', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '제육덮밥', 5500, 's42', 3, '제육덮밥입니다.', '제육덮밥', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 03, '곱배기', 1000, 's42', 3, '면과 밥류에만 곱배기가 추가됩니다.', '곱배기', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '왕만두튀김', 2000, 's42', 3, '왕만두튀김입니다.', '왕만두튀김', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '매콤닭다리', 2500, 's42', 3, '매콤닭다리입니다.', '매콤닭다리', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '음료', 2000, 's42', 3, '350ml 콜라와 사이다만 판매합니다.', '콜라, 사이다', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '주류', 4000, 's42', 3, '맥주와 소주만 판매합니다.', '소주, 맥주', null, null);

INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '로스까스', 4000, 's58', 3, NULL, NULL, null, '\img\menu\stest18\로스까스.png');
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '히레까스', 5000, 's58', 3,  NULL, NULL, null, '\img\menu\stest18\히레까스.png');
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '치즈돈까스', 4500, 's58', 3,  NULL, NULL, null, '\img\menu\stest18\치즈돈까스.png');
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '고구마 치즈돈까스', 5000, 's58', 3, NULL, NULL, null, '\img\menu\stest18\고치돈.png');
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '생선까스', 4000, 's58', 3, NULL, NULL, null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '치킨까스', 4000, 's58', 3, NULL, NULL, null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '가츠동', 3000, 's58', 3, NULL, NULL, null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '에비동', 3000, 's58', 3, NULL, NULL, null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '미니우동', 1000, 's58', 3, NULL, NULL, null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '새우튀김', 2000, 's58', 3, NULL, NULL, null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '가라아게', 2000, 's58', 3, NULL, NULL, null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '콜라', 1500, 's58', 3, NULL, NULL, null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '사이다', 1500, 's58', 3, NULL, NULL, null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '맥주', 2000, 's58', 3, NULL, NULL, null, null);

-- 양식 판매자 메뉴 등록
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '매운크림파스타', 7000, 's121', 4, '매운크림파스타입니다.', '매운크림파스타', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '간장우삼겹파스타', 7000, 's121', 4, '간장우삼겹파스타입니다.', '간장우삼겹파스타', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '까르보나라', 6500, 's121', 4, '까르보나라입니다.', '까르보나라', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '로제크림파스타', 7000, 's121', 4, '로제크림파스타입니다.', '로제크림파스타', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '고르곤졸라', 6500, 's121', 4, '고르곤졸라입니다.', '고르곤졸라', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '마르게리따', 6000, 's121', 4, '마르게리따입니다.', '마르게리따', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '크림치즈 샐러드', 4000, 's121', 4, '크림치즈 샐러드입니다.', '크림치즈 샐러드', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '그린샐러드', 3000, 's121', 4, '그린샐러드입니다.', '그린샐러드', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '음료', 2000, 's121', 4, '350ml 콜라와 사이다만 판매합니다.', '콜라, 사이다', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '에이드', 4000, 's121', 4, '청포도, 자몽, 레몬에이드 있습니다.', '청포도, 자몽, 레몬', null, null);

INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '핫쉬림프파스타', 3500, 's122', 4, '핫쉬림프파스타입니다.', '핫쉬림프파스타', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '해물누룽지파스타', 5000, 's122', 4, '해물누룽지파스타입니다.', '해물누룽지파스타', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '바비큐폭립스테이크', 5500, 's122', 4, '바비큐폭립스테이크입니다.', '바비큐폭립스테이크', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '트리플목살스테이크', 4000, 's122', 4, '트리플목살스테이크입니다.', '트리플목살스테이크', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '매콤해물필라프', 5500, 's122', 4, '매콤해물필라프입니다.', '매콤해물필라프', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '스파이시치킨필라프', 1000, 's122', 4, '스파이시치킨필라프입니다.', '스파이시치킨필라프', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '치즈볼', 2000, 's122', 4, '치즈볼입니다.', '치즈볼', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '웨지감자', 2500, 's122', 4, '웨지감자입니다.', '웨지감자', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '음료', 2000, 's122', 4, '350ml 콜라와 사이다만 판매합니다.', '콜라, 사이다', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '주류', 4000, 's122', 4, '맥주와 소주만 판매합니다.', '소주, 맥주', null, null);

-- 치킨 판매자 메뉴 등록
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '크리스피 치킨', 7000, 's1', 5, '크리스피 치킨입니다.', '크리스피 치킨', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '달달 간장치킨', 7000, 's1', 5, '달달 간장치킨입니다.', '달달 간장치킨', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '매콤 양념치킨', 7000, 's1', 5, '매콤 양념치킨입니다.', '매콤 양념치킨', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '갈릭치킨', 7000, 's1', 5, '갈릭치킨입니다.', '갈릭치킨', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 03, '반마리 추가', 3000, 's1', 5, '치킨 양을 추가합니다.', '반마리 추가', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '치즈스틱', 2000, 's1', 5, '치즈스틱입니다.', '치즈스틱2EA', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '치즈볼', 5000, 's1', 5, '치즈볼입니다.', '치즈볼5EA', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '감자튀김', 4000, 's1', 5, '감자튀김입니다.', '감자튀김', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '음료', 2000, 's1', 5, '350ml 콜라와 사이다만 판매합니다.', '콜라, 사이다', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '주류', 4000, 's1', 5, '맥주와 소주만 판매합니다.', '소주, 맥주', null, null);

INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '빠네치킨', 8000, 's2', 5, '빠네와 치킨의 조합 빠네치킨입니다.', '빠네치킨', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '피코치킨', 9000, 's2', 5, '크리스피, 칠리, 허니갈릭 3가지를 동시에 맛볼수 있는 치킨입니다.', '피코치킨', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '순살크리스피치킨', 6500, 's2', 5, '순살크리스피치킨입니다.', '순살크리스피치킨', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '순살칠리치킨', 6500, 's2', 5, '순살칠리치킨입니다.', '순살칠리치킨', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '순살허니갈릭치킨', 6500, 's2', 5, '순살허니갈릭치킨입니다.', '순살허니갈릭치킨', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '고르곤졸라', 5000, 's2', 5, '고르곤졸라입니다.', '고르곤졸라', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '치즈피자', 5000, 's2', 5, '치즈피자입니다.', '치즈피자', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '감자튀김', 3000, 's2', 5, '감자튀김입니다.', '감자튀김', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '음료', 2000, 's2', 5, '350ml 콜라와 사이다만 판매합니다.', '콜라, 사이다', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '주류', 4000, 's2', 5, '맥주와 소주만 판매합니다.', '소주, 맥주', null, null);

-- 디저트 판매자 메뉴 등록
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '얼그레이풀', 7000, 's21', 6, '생크림 가득한 수플레 팬케이크입니다.', '얼그레이풀', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '플라이 망고', 7000, 's21', 6, '망고가 더해진 수플레 펜케이크입니다.', '플라이 망고', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '바나나 웍스', 7000, 's21', 6, '바나나가 더해진 수플레 펜케이크입니다.', '바나나 웍스', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '베리 나이스데이', 7000, 's21', 6, '각종 베리가 더해진 수플레 펜케이크입니다.', '베리 나이스데이', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '파인 티라미수', 3000, 's21', 6, '티라미수 케이크입니다.', '파인 티라미수', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '아메리카노', 2000, 's21', 6, '아메리카노입니다.', '아메리카노', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '카페라떼', 2500, 's21', 6, '카페라떼입니다.', '카페라떼', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '카푸치노', 2500, 's21', 6, '카푸치노입니다.', '카푸치노', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '카페모카', 2500, 's21', 6, '카페모카입니다.', '카페모카', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '얼그레이', 2500, 's21', 6, '얼그레이입니다.', '얼그레이', null, null);

INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '스트로베리 치즈케익 와플', 5000, 's22', 6, '스트로베리 치즈케익 와플입니다.', '스트로베리 치즈케익 와플', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '크로플', 5000, 's22', 6, '제철 과일을 듬뿍올린 와플입니다.', '크로플', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '아이스크림 와플', 4500, 's22', 6, '아이스크림 와플입니다.', '아이스크림 와플', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '오레오초코칩와플', 4500, 's22', 6, '오레오초코칩와플입니다.', '오레오초코칩와플', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '치즈케이크와플', 4000, 's22', 6, '치즈케이크와플입니다.', '치즈케이크와플', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '플레인와플', 3000, 's22', 6, '플레인와플입니다.', '플레인와플', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '브라우니', 3000, 's22', 6, '브라우니입니다.', '브라우니', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '요거트스무디', 4000, 's22', 6, '요거트스무디입니다.', '요거트스무디', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '오레오스무디', 4000, 's22', 6, '오레오스무디입니다.', '오레오스무디', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '딸기스무디', 4000, 's22', 6, '딸기스무디입니다.', '딸기스무디', null, null);

-- 주류 판매자 메뉴 등록
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '버드와이저', 3000, 's61', 7, '라거 맥주입니다.', '버드와이저', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '하이네켄', 3000, 's61', 7, '라거 맥주입니다.', '하이네켄', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '하얼빈브루어리', 3000, 's61', 7, '라거 맥주입니다.', '매콤 양념치킨', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '기린', 3000, 's61', 7, '라거 맥주입니다.', '기린', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '코로나', 3000, 's61', 7, '라거 맥주입니다.', '코로나', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '페일에일', 3000, 's61', 7, '에일 맥주입니다.', '페일에일', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '인디아페일에일', 3000, 's61', 7, '에일 맥주입니다.', '인디아페일에일', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '앰버에일', 3000, 's61', 7, '에일 맥주입니다.', '앰버에일', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '강서에일', 3000, 's61', 7, '에일 맥주입니다.', '강서에일', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '런던프라이드', 3000, 's61', 7, '에일 맥주입니다.', '런던프라이드', null, null);

INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '피치크러쉬', 5500, 's90', 7, '피치크러쉬입니다.', '피치크러쉬', null, '\img\menu\alcohol03\피치크러쉬.jpg');
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '블루 하와이', 6500, 's90', 7, '블루 하와이입니다.', '블루 하와이', null, '\img\menu\alcohol03\블루 하와이.jpg');
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '감자튀김', 3800, 's90', 7, null, null, null, '\img\menu\alcohol03\감자튀김.jpg');
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '깔루아 커피', 4300, 's90', 7, '깔루아 커피입니다.', '깔루아 커피', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '코스모폴리탄', 5100, 's90', 7, '코스모폴리탄입니다.', '코스모폴리탄', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '피나 콜라다', 6100, 's90', 7, '피나 콜라다입니다.', '피나 콜라다', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '준벅', 6900, 's90', 7, '준벅입니다.', '준벅', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '오렌지 블러썸', 3800, 's90', 7, '오렌지 블러썸입니다.', '오렌지 블러썸', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '마티니', 4000, 's90', 7, '마티니입니다.', '마티니', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '소세지', 3800, 's90', 7, '소세지입니다.', '소세지', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '버팔로윙', 3800, 's90', 7, '버팔로윙', '버팔로윙', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '치즈', 3800, 's90', 7, '치즈', '버팔로윙', null, null);

-- 패스트푸드 판매자 메뉴 등록
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '더블불고기 버거', 5000, 's141', 8, '더블패티 불고기 버거입니다.', '더블불고기 버거', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '통살 치킨버거', 5000, 's141', 8, '통살 치킨버거입니다.', '통살 치킨버거', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '매콤 데리야끼버거', 4000, 's141', 8, '매콤한 데리야끼버거입니다.', '매콤 데리야끼버거', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '갈릭치킨버거', 6000, 's141', 8, '갈릭치킨버거입니다.', '갈릭치킨버거', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '닭다리', 2500, 's141', 8, '닭다리입니다.', '닭다리', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '치즈스틱', 2000, 's141', 8, '치즈스틱입니다.', '치즈스틱2EA', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '치즈볼', 5000, 's141', 8, '치즈볼입니다.', '치즈볼5EA', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '감자튀김', 1000, 's141', 8, '감자튀김입니다.', '감자튀김', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '음료', 2000, 's141', 8, '350ml 콜라와 사이다만 판매합니다.', '콜라, 사이다', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '주류', 4000, 's141', 8, '맥주와 소주만 판매합니다.', '소주, 맥주', null, null);

INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '치즈피자', 5000, 's142', 8, '치즈피자입니다.', '치즈피자', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 01, '페퍼로니 피자', 5500, 's142', 8, '페퍼로니 피자입니다.', '페퍼로니 피자', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '핫치킨 피자', 7000, 's142', 8, '핫치킨 피자입니다.', '핫치킨 피자', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '고구마피자', 6000, 's142', 8, '고구마피자입니다.', '고구마피자', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '포테이토피자', 6000, 's142', 8, '포테이토피자입니다.', '포테이토피자', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 02, '고르곤졸라', 5000, 's142', 8, '고르곤졸라입니다.', '고르곤졸라', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '치즈볼', 5000, 's142', 8, '치즈볼입니다.', '치즈볼5EA', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 04, '감자튀김', 3000, 's142', 8, '감자튀김입니다.', '감자튀김', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '음료', 2000, 's142', 8, '350ml 콜라와 사이다만 판매합니다.', '콜라, 사이다', null, null);
INSERT INTO MENU (MENU_CODE, SUBMENU_CODE, MENU_NAME, PRICE, S_CODE, CATEGORY_CODE, DETAIL, SUMMARY, MENU_PHOTO, MENU_PHOTO_PATH)
VALUES (MENU_SEQ.NEXTVAL, 05, '주류', 4000, 's142', 8, '맥주와 소주만 판매합니다.', '소주, 맥주', null, null);
COMMIT;
SELECT * FROM MENU;