INSERT INTO ORDER_TBL VALUES(ORDER_SEQ.NEXTVAL,'admin',RECEIPT_SEQ.NEXTVAL,21,'마라탕',5000,3,'주문','현장결제','s101','lovemara','맛있게 해주세요~',SYSDATE);
INSERT INTO ORDER_TBL VALUES(ORDER_SEQ.NEXTVAL,'admin',RECEIPT_SEQ.CURRVAL,22,'쌀국수',4000,2,'주문','현장결제','s101','lovemara','맛있게 해주세요~',SYSDATE);
INSERT INTO ORDER_TBL VALUES(ORDER_SEQ.NEXTVAL,'admin',RECEIPT_SEQ.CURRVAL,23,'마라샹궈',7000,1,'주문','현장결제','s101','lovemara','맛있게 해주세요~',SYSDATE);

INSERT INTO ORDER_TBL VALUES(ORDER_SEQ.NEXTVAL,'admin',RECEIPT_SEQ.NEXTVAL,21,'마라탕',5000,4,'수락','현장결제','s101','lovemara','맛있게 해라',SYSDATE);
INSERT INTO ORDER_TBL VALUES(ORDER_SEQ.NEXTVAL,'admin',RECEIPT_SEQ.CURRVAL,22,'쌀국수',4000,1,'수락','현장결제','s101','lovemara','맛있게 해라',SYSDATE);
INSERT INTO ORDER_TBL VALUES(ORDER_SEQ.NEXTVAL,'admin',RECEIPT_SEQ.CURRVAL,23,'마라샹궈',7000,1,'수락','현장결제','s101','lovemara','맛있게 해라',SYSDATE);

INSERT INTO ORDER_TBL VALUES(ORDER_SEQ.NEXTVAL,'test2',RECEIPT_SEQ.NEXTVAL,21,'마라탕',5000,3,'완료','현장결제','s101','lovemara','잘해줘 ㅡㅡ',SYSDATE);
INSERT INTO ORDER_TBL VALUES(ORDER_SEQ.NEXTVAL,'test2',RECEIPT_SEQ.CURRVAL,22,'쌀국수',4000,2,'완료','현장결제','s101','lovemara','잘해줘 ㅡㅡ',SYSDATE);
INSERT INTO ORDER_TBL VALUES(ORDER_SEQ.NEXTVAL,'test2',RECEIPT_SEQ.CURRVAL,23,'마라샹궈',7000,1,'완료','현장결제','s101','lovemara','잘해줘 ㅡㅡ',SYSDATE);

INSERT INTO ORDER_TBL VALUES(ORDER_SEQ.NEXTVAL,'admin',RECEIPT_SEQ.NEXTVAL,4,'모둠볶음',5000,3,'주문','현장결제','s81','곱창볶음굳','맛있게 해주세요~',SYSDATE);
INSERT INTO ORDER_TBL VALUES(ORDER_SEQ.NEXTVAL,'admin',RECEIPT_SEQ.CURRVAL,5,'소곱창',4000,2,'주문','현장결제','s81','곱창볶음굳','맛있게 해주세요~',SYSDATE);
INSERT INTO ORDER_TBL VALUES(ORDER_SEQ.NEXTVAL,'admin',RECEIPT_SEQ.CURRVAL,6,'볶음밥',7000,1,'주문','현장결제','s81','곱창볶음굳','맛있게 해주세요~',SYSDATE);

INSERT INTO ORDER_TBL VALUES(ORDER_SEQ.NEXTVAL,'test1',RECEIPT_SEQ.NEXTVAL,1,'곱창',7000,3,'주문','현장결제','s81','곱창볶음굳','맛있게 해주세요~',SYSDATE);
INSERT INTO ORDER_TBL VALUES(ORDER_SEQ.NEXTVAL,'test1',RECEIPT_SEQ.CURRVAL,2,'막창',9000,2,'주문','현장결제','s81','곱창볶음굳','맛있게 해주세요~',SYSDATE);
INSERT INTO ORDER_TBL VALUES(ORDER_SEQ.NEXTVAL,'test1',RECEIPT_SEQ.CURRVAL,3,'대창',9000,1,'주문','현장결제','s81','곱창볶음굳','맛있게 해주세요~',SYSDATE);

INSERT INTO LASTORDER VALUES(LASTORDER_SEQ.NEXTVAL, 10, 20, '매콤 양념치킨', 7000, 's1', 5, '매콤 양념치킨입니다.', '매콤 양념치킨', null, null, 2);
INSERT INTO LASTORDER VALUES(LASTORDER_SEQ.NEXTVAL, 10, 20, '갈릭치킨', 7000, 's1', 5, '갈릭치킨입니다.', '갈릭치킨', null, null, 2);

commit;
